name: 10 MB file size limit
on:
  pull_request:
    branches: [main]

jobs:
  check-file-sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
