name: Push to HuggingFace Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

    - name: Push to HuggingFace Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git push https://joshuasundance:$HF_TOKEN@huggingface.co/spaces/joshuasundance/streamlit-gpt4o main
